// Private consultation and health diary. Provider imports retain provenance.
export function installConsultation(app, d) {
 const {db,id,now,hash,records,saveRecord,record,transaction,audit,requireUser,coach,wrap,fail,text}=d;
 const fields=['age','height','weight','targetWeight','goal','activity','diet','allergies','meals','preferences','conditions','medications','injuries','sleep','water','routine','expectations'];
 const numeric={age:[18,100],height:[100,250],weight:[20,400],targetWeight:[20,400],sleep:[0,24],water:[0,15],steps:[0,100000],waist:[30,250],energy:[1,5]};
 function number(v,k,required=false){if(v===''||v==null){if(required)fail(`${k} is required.`);return null;} if(!['string','number'].includes(typeof v))fail(`Please check ${k}.`);const n=Number(v),[min,max]=numeric[k];if(!Number.isFinite(n)||n<min||n>max||(k==='age'&&!Number.isInteger(n)))fail(`Please check ${k} (${min}–${max}).`);return n;}
 function diary(b){const date=text(b.date,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date))||new Date(date).toISOString().slice(0,10)!==date||date>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'}))fail('Use a valid date, today or earlier.'); const x={date};for(const k of ['weight','sleep','water','steps','waist','energy'])x[k]=number(b[k],k);x.note=text(b.note,2000);if(!x.note&&!Object.values(x).some(v=>typeof v==='number'))fail('Add a measurement or a note.');return x;}
 const data=owner=>({intakes:records('consultations',owner),entries:records('health_diary',owner)});
 app.get('/api/client/health',requireUser,wrap((q,r)=>r.json(data(q.user.id))));
 app.post('/api/client/consultation',requireUser,wrap((q,r)=>{if(q.body.consent!==true)fail('Please consent to sharing this consultation with your coach.');const b={};for(const k of fields)b[k]=numeric[k]?number(q.body[k],k,['age','height','weight'].includes(k)):text(q.body[k],2000);if(!b.goal)fail('Please tell us your goal.');b.consentAt=now();b.consentVersion='health-v1';r.json(saveRecord('consultations',id(),b,q.user.id));audit(q.user.id,'consultation.saved');}));
 app.post('/api/client/health/entry',requireUser,wrap((q,r)=>r.json(saveRecord('health_diary',id(),{...diary(q.body),source:'Manual'},q.user.id))));
 app.put('/api/client/health/entry/:id',requireUser,wrap((q,r)=>{const old=record(q.params.id);if(old?.kind!=='health_diary'||old.owner!==q.user.id)fail('Record not found.',404);r.json(saveRecord('health_diary',old.id,{...diary(q.body),source:old.source,edited:true},q.user.id));}));
 app.delete('/api/client/health/:kind/:id',requireUser,wrap((q,r)=>{const old=record(q.params.id);if(!['consultations','health_diary'].includes(q.params.kind)||old?.kind!==q.params.kind||old.owner!==q.user.id)fail('Record not found.',404);db.prepare('DELETE FROM records WHERE id=?').run(old.id);audit(q.user.id,'health.deleted',old.id);r.json({ok:true});}));
 app.post('/api/client/health/import',requireUser,wrap((q,r)=>{if(q.body.consent!==true)fail('Please approve this import.');if(!Array.isArray(q.body.entries)||!q.body.entries.length||q.body.entries.length>1000)fail('Import 1–1,000 records at a time.');const source=text(q.body.source,100)||'CSV import';const entries=q.body.entries.map(diary);let added=0;transaction(()=>{for(const entry of entries){const key='health-'+hash(q.user.id+JSON.stringify(entry)+source);if(record(key))continue;saveRecord('health_diary',key,{...entry,source},q.user.id);added++;}});audit(q.user.id,'health.imported',String(added));r.json({added,skipped:entries.length-added});}));
 app.get('/api/admin/clients/:id/health',coach,wrap((q,r)=>{const u=db.prepare("SELECT id FROM users WHERE id=? AND role='client'").get(q.params.id);if(!u)fail('Client not found.',404);audit(q.user.id,'health.viewed',u.id);r.json(data(u.id));}));
}
