export const initialSettings = {
  travelCards: [{"image": "/images/surya/travel-mirror-original.png", "location": "Mumbai, India", "caption": "Same me, stronger every day."}, {"image": "/images/surya/surya-seaside.jpeg", "location": "Goa, India", "caption": "Vitamin sea & bigger dreams."}, {"image": "/images/surya/travel-city.jpeg", "location": "Almaty, Kazakhstan", "caption": "Different places. Same goals."}, {"image": "/images/surya/travel-garden.jpeg", "location": "Jim Corbett Park, India", "caption": "Fresh air. Clearer thoughts."}, {"image": "/images/surya/surya-portrait-natural.jpeg", "location": "Phuket, Thailand", "caption": "Make room for yourself."}, {"image": "/images/surya/hero-outdoor-original.jpeg", "location": "Mumbai, India", "caption": "A little joy along the way."}, {"image": "/images/surya/travel-cafe.jpeg", "location": "Somewhere happy", "caption": "Good moments. A fuller life."}],
  brand: "Train with Surya",
  tagline: "Stronger every day. With Surya.",
  email: "surya737singh@gmail.com",
  whatsapp: "918299375609",
  location: "",
  instagram: "https://www.instagram.com/surya.singhhhh/",
  facebook: "https://www.facebook.com/surya.singh.928762",
  portrait: "/images/surya/coach-blue.webp",
  heroImage: "/images/surya/hero-selected.png",
  heroVideo: "",
  thirdHeroImage: "/images/surya/hero-lifestyle-olive.webp",
  secondHeroImage: "/images/surya/hero-outdoor-original.jpeg",
  logoImage: "/images/brand/surya-logo-light.png",
  footerLogoImage: "/images/brand/surya-logo-white.png",
  coachImage: "/images/surya/coach-blue.webp",
  visualTheme: "slate-blue-reference-2026-09-29",
  hero: [
    {
      eyebrow: "FITNESS  •  NUTRITION  •  MINDSET  •  LIFESTYLE",
      title: "Stronger\nHealthier\nHappier You.",
      text: "Personal training, practical nutrition guidance and a plan built around your life. Let’s make your next chapter a strong one.",
      cta: "Explore Programmes",
      href: "/programmes",
    },
{
  "eyebrow": "FITNESS  \u2022  NUTRITION  \u2022  MINDSET  \u2022  LIFESTYLE",
  "title": "Stronger\nHealthier\nHappier You.",
  "text": "Real training. Practical nutrition. A lifestyle you can actually follow. Let\u2019s make your next chapter a stronger one.",
  "cta": "Explore Programmes",
  "href": "/programmes"
},
    {
      eyebrow: "CONFIDENCE  •  BALANCE  •  EVERYDAY JOY",
      title: "Feel good.\nLive fully.\nBe yourself.",
      text: "Build strength for the life you love. Simple movement, balanced nutrition and personal support to help you feel confident in your own skin.",
      cta: "Find Your Balance",
      href: "/programmes",
    },
  ],
  aboutTitle: "She knows what\nstarting feels like.",
  aboutText:
    "Surya’s approach to coaching starts with understanding. Her own fitness journey taught her the value of showing up, building confidence and making progress one step at a time. Now she brings that personal perspective to every coaching conversation.",
  sections: [
    {
      id: "programmes",
      title: "A little direction.\nA stronger you.",
      subtitle:
        "There is more than one way to move forward. Find the support that works for you.",
      enabled: true,
    },
    {
      id: "about",
      title: "She knows what\nstarting feels like.",
      subtitle: "A coach who understands the journey.",
      enabled: true,
    },
    {
      id: "method",
      title: "Big changes start\nwith small steps.",
      subtitle: "No guessing. No going it alone. Just a clear path forward.",
      enabled: true,
    },
    {
      id: "transformations",
      title: "Progress looks\ndifferent on everyone.",
      subtitle:
        "Strength, confidence, consistency. Your story is more than a number.",
      enabled: true,
    },
    {
      id: "journal",
      title: "A little knowledge.\nA lot of possibility.",
      subtitle: "Thoughtful reads for a stronger everyday.",
      enabled: true,
    },
    {
      id: "social",
      title: "Life beyond\nthe workout.",
      subtitle: "Follow the moments, movement and mindset behind the coaching.",
      enabled: true,
    },
  ],
  consultationMinutes: 30,
  bufferMinutes: 15,
  cancellationHours: 24,
  reminderHours: 24,
  bookingMode: "request",
  popupEnabled: false,
  popupDelay: 35,
  privacyContact: "",
  seoTitle: "Train With Surya — Your Stronger Chapter",
  seoDescription:
    "Personal training, online coaching, home workouts and practical nutrition support with Surya Singh.",
  finderRules: [
    {
      field: "goal",
      value: "Weight management",
      programme: "weight-management",
    },
    { field: "location", value: "Home", programme: "home-workouts" },
    { field: "format", value: "Online coaching", programme: "online-coaching" },
    {
      field: "goal",
      value: "Nutrition habits",
      programme: "nutrition-support",
    },
  ],
};
export const programmes = [
  {
    id: "personal-training",
    title: "One-to-one\npersonal training",
    category: "One-to-One",
    label: "FOCUS ON YOU",
    summary: "Your goals. Your pace. Your coach, right beside you.",
    description:
      "Individual attention, thoughtful progression and coaching that begins with understanding your starting point. Explore a personal training approach built around your goals and experience.",
    inclusions: [
      "Personal goal-setting conversation",
      "Technique-focused coaching",
      "An individual training approach",
      "Progress reviews and adjustments",
    ],
    suitable: "People who value individual guidance and feedback.",
    mode: "In-person, subject to confirmed location",
    equipment: "Discuss during your consultation",
    price: null,
    duration: "Discuss with Surya",
    frequency: "Personalised after consultation",
    support: "Agreed with your coach before enrolment",
    status: "published",
    order: 1,
    icon: "dumbbell",
    color: "sage",
    faq: [
      {
        question: "Where are sessions held?",
        answer:
          "Enquire to confirm current training locations and availability.",
      },
    ],
  },
  {
    id: "online-coaching",
    title: "Online\npersonal coaching",
    category: "Online",
    label: "YOUR COACH, WHEREVER YOU ARE",
    summary: "A clear plan and genuine support, wherever life takes you.",
    description:
      "Bring structure to your training with remote coaching, exercise guidance and check-ins. Your programme and support schedule are agreed together before you start.",
    inclusions: [
      "Initial coaching conversation",
      "Individual workout schedule",
      "Exercise guidance",
      "Scheduled progress check-ins",
    ],
    suitable: "Busy people who want guidance with flexibility.",
    mode: "Online",
    equipment: "Adapted to your available equipment",
    price: null,
    duration: "Discuss with Surya",
    frequency: "Agreed before enrolment",
    support: "Check-in schedule confirmed before enrolment",
    status: "published",
    order: 2,
    icon: "monitor",
    color: "cream",
    faq: [
      {
        question: "Are live video sessions included?",
        answer:
          "Ask Surya about available formats. Live sessions are included only when specified in your selected plan.",
      },
    ],
  },
  {
    id: "home-workouts",
    title: "Home-based\nworkouts",
    category: "At Home",
    label: "YOUR SPACE. YOUR STRENGTH.",
    summary: "Make room for movement. Start right where you are.",
    description:
      "Explore a practical routine around your space, schedule and available equipment. Get a clear starting point and guidance as you build consistency.",
    inclusions: [
      "Equipment and space assessment",
      "A routine that fits your available time",
      "Exercise alternatives",
      "Coach-reviewed progression",
    ],
    suitable: "Beginners and anyone who prefers training at home.",
    mode: "At home with remote guidance",
    equipment: "Bodyweight or available home equipment",
    price: null,
    duration: "Discuss with Surya",
    frequency: "Personalised after consultation",
    support: "Agreed before enrolment",
    status: "published",
    order: 3,
    icon: "home",
    color: "peach",
    faq: [],
  },
  {
    id: "weight-management",
    title: "Sustainable\nweight management",
    category: "Weight Management",
    label: "PROGRESS, WITHOUT THE PRESSURE",
    summary: "Build habits for your life, not just a moment on the scales.",
    description:
      "Work towards your goals through consistent movement, strength training and practical habits. Progress is individual, and your starting point matters.",
    inclusions: [
      "Personal goal discussion",
      "Structured movement and strength work",
      "Habit-focused support",
      "Regular progress conversations",
    ],
    suitable: "People seeking a consistent and supportive approach.",
    mode: "Discuss online or personal coaching",
    equipment: "Adapted to your programme",
    price: null,
    duration: "Discuss with Surya",
    frequency: "Personalised after consultation",
    support: "Agreed before enrolment",
    status: "published",
    order: 4,
    icon: "activity",
    color: "sage",
    faq: [
      {
        question: "Is weight loss guaranteed?",
        answer:
          "No. Results vary with individual circumstances, consistency and other factors. We agree realistic goals together.",
      },
    ],
  },
  {
    id: "nutrition-support",
    title: "Nutrition &\ndiet-chart support",
    category: "Nutrition",
    label: "EVERYDAY FOOD. PRACTICAL HABITS.",
    summary: "Guidance that makes room for your preferences and real life.",
    description:
      "Discuss everyday eating habits, preferences and a practical approach with Surya. Personalised nutrition services are offered within the coach’s verified scope; medical dietary needs require an appropriately qualified professional.",
    inclusions: [
      "Food and lifestyle preferences",
      "Practical meal-planning discussion",
      "Meal options and substitutions within scope",
      "Coach-reviewed adjustments",
    ],
    suitable: "People looking for practical everyday nutrition support.",
    mode: "Personal consultation",
    equipment: "No equipment needed",
    price: null,
    duration: "Discuss with Surya",
    frequency: "Agreed before enrolment",
    support: "Professional scope confirmed before assignment",
    status: "published",
    order: 5,
    icon: "leaf",
    color: "cream",
    faq: [],
  },
];
export const draftArticles = [
  "Starting Strength Training When You Feel Unsure",
  "Building a Home Workout Routine You Can Maintain",
  "Progress Beyond the Weighing Scale",
  "Practical Meal Planning Around a Busy Schedule",
  "What to Expect from Personal Coaching with Surya",
].map((title, i) => ({
  id: `article-${i + 1}`,
  title,
  status: "draft",
  excerpt: "Editorial draft topic awaiting coach review.",
  body: "",
  bodyHi: "",
  titleHi: "",
  image: "",
  category: i === 3 ? "Nutrition" : "Mindset",
  author: "Surya Singh",
  publishedAt: "",
  readTime: "",
  order: i,
}));
