import { LoginExperience } from "./login-experience";
import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {Heart,ShieldCheck,Activity,Upload,ArrowUpRight} from 'lucide-react';
import {api,post,useSite,useAction,Status,Field,Entry,download,parseCSV} from './lib';
import './consultation.css';
const groups=[
 ['Your starting point',[['age','Age (years)*','number'],['height','Height (cm)*','number'],['weight','Current weight (kg)*','number'],['targetWeight','Target weight (kg), optional','number'],['goal','Your goals*','textarea'],['activity','Activity level','select','Mostly seated|Lightly active|Moderately active|Very active']]],
 ['Food & everyday life',[['diet','Food preference','select','No preference|Vegetarian|Vegan|Eggetarian|Non-vegetarian'],['allergies','Food allergies / intolerances','textarea'],['meals','Usual meals, timing & eating out','textarea'],['preferences','Foods you enjoy or avoid','textarea'],['sleep','Average sleep (hours)','number'],['water','Daily water (litres)','number'],['routine','Work, routine & exercise habits','textarea']]],
 ['Health & support · optional',[['conditions','Health conditions or recent test results','textarea'],['medications','Medications / supplements','textarea'],['injuries','Injuries, pain or movement limitations','textarea'],['expectations','Anything else your coach should know','textarea']]],
] as any[];
const limits:Entry={age:[18,100],height:[100,250],weight:[20,400],targetWeight:[20,400],sleep:[0,24],water:[0,15],steps:[0,100000],waist:[30,250],energy:[1,5]};
const today=()=>new Date().toLocaleDateString('en-CA');
export function Consultation({embedded=false}:{embedded?:boolean}){
 const {user,setUser}=useSite(),a=useAction();const [d,setD]=useState<Entry|null>(null),[tab,setTab]=useState('consultation'),[form,setForm]=useState<Entry>({}),[entry,setEntry]=useState<Entry>({date:today()}),[preview,setPreview]=useState<Entry[]>([]),[source,setSource]=useState('CSV import'),[approved,setApproved]=useState(false);
 const load=()=>api('/client/health').then(x=>{setD(x);setForm(x.intakes[0]||{});});useEffect(()=>{if(user)load().catch(e=>a.setError(e.message));},[user?.id]);
 const save=async(fn:()=>Promise<any>,message:string)=>{const r=await a.run(fn,message);if(r)await load();return r;};
 async function importFile(file?:File){setPreview([]);setApproved(false);if(!file)return;try{if(file.size>15*1024*1024)throw Error('Choose a file smaller than 15 MB. Split larger exports first.');const text=await file.text();let rows:Entry[]=[];
 if(file.name.toLowerCase().endsWith('.xml')){const xml=new DOMParser().parseFromString(text,'text/xml');if(xml.querySelector('parsererror'))throw Error('This XML file could not be read.');for(const n of Array.from(xml.querySelectorAll('Record'))){const type=n.getAttribute('type'),unit=n.getAttribute('unit'),value=Number(n.getAttribute('value'));if(type==='HKQuantityTypeIdentifierBodyMass'&&['kg','lb'].includes(unit||''))rows.push({date:n.getAttribute('startDate')?.slice(0,10),weight:unit==='lb'?Math.round(value*.45359237*100)/100:value});}setSource('Apple Health XML · weight');if(!rows.length)throw Error('No supported body-weight records found (kg or lb).');}
 else{rows=parseCSV(text);setSource('CSV import');}if(!rows.length||rows.length>1000)throw Error('Choose 1–1,000 records per import.');setPreview(rows);}catch(e:any){a.setError(e.message);}}
 if(!user)return <LoginExperience onSuccess={setUser}/>;
 return <section className={'consultation '+(embedded?'embedded':'wrap')}>
 {!embedded&&<header className="health-intro"><span className="eyebrow">YOUR PRIVATE COACHING SPACE</span><h1>A little about you.<br/><em>A better plan for you.</em></h1><p>Nutrition, movement and everyday habits. Start with your story and keep track of what matters to you.</p><Link to="/book" className="text-link">Book a consultation <ArrowUpRight size={18}/></Link></header>}
 <Status action={a}/>
 {!d?<p>Loading your private records…</p>:<>
 <nav className="health-tabs" aria-label="Health records">{[['consultation','Consultation'],['diary','Daily diary'],['connections','Health imports']].map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>{setTab(key);a.setSuccess('');a.setError('');}}>{label}</button>)}<button onClick={()=>download('my-health-records.json',JSON.stringify(d,null,2),'application/json')}>Export records</button></nav>
 {tab==='consultation'&&<form className="health-form" onSubmit={e=>{e.preventDefault();save(()=>post('/client/consultation',{...form,consent:new FormData(e.currentTarget).get('consent')==='on'}),'Consultation saved. Your coach can review it.');}}><div className="health-heading"><Heart/><div><h2>Let’s understand your starting point.</h2><p>* Required. Share only what you are comfortable sharing. Each save keeps a dated version.</p></div></div>{groups.map(([heading,fields]:any)=><fieldset key={heading}><legend>{heading}</legend><div className="health-fields">{fields.map(([key,label,type,options]:string[])=><Field key={key} label={label}>{type==='textarea'?<textarea value={form[key]||''} maxLength={2000} required={key==='goal'} onChange={e=>setForm({...form,[key]:e.target.value})}/>:type==='select'?<select value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}><option value="">Choose / prefer not to say</option>{options.split('|').map(x=><option key={x}>{x}</option>)}</select>:<input type="number" step={key==='age'?1:'any'} min={limits[key][0]} max={limits[key][1]} required={['age','height','weight'].includes(key)} value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</Field>)}</div></fieldset>)}<label className="health-check"><input type="checkbox" name="consent" required/>I consent to storing this information and sharing it with Surya’s authorised coaching team for my consultation.</label><button className="button" disabled={a.busy}>Save consultation</button>{d.intakes.length>0&&<details><summary>Saved consultations ({d.intakes.length})</summary>{d.intakes.map((x:Entry)=><div className="health-record" key={x.id}><span>{new Date(x.created).toLocaleString()} · {x.goal}</span><button type="button" onClick={()=>{if(confirm('Delete this saved consultation?'))save(()=>post('/client/health/consultations/'+x.id,{},'DELETE'),'Deleted.');}}>Delete</button></div>)}</details>}</form>}
 {tab==='diary'&&<div className="health-form"><div className="health-heading"><Activity/><div><h2>Your daily check-in.</h2><p>Small observations, at your own pace. All measurements are optional and visible to your authorised coaching team.</p></div></div><form onSubmit={async e=>{e.preventDefault();if(await save(()=>post('/client/health/entry'+(entry.id?'/'+entry.id:''),entry,entry.id?'PUT':'POST'),'Diary saved.'))setEntry({date:today()});}}><div className="health-fields"><Field label="Date"><input type="date" required max={today()} value={entry.date} onChange={e=>setEntry({...entry,date:e.target.value})}/></Field>{[['weight','Weight (kg)'],['waist','Waist (cm)'],['sleep','Sleep (hours)'],['water','Water (litres)'],['steps','Steps'],['energy','Energy (1–5)']].map(([key,label])=><Field key={key} label={label}><input type="number" step={['steps','energy'].includes(key)?1:'any'} min={limits[key][0]} max={limits[key][1]} value={entry[key]??''} onChange={e=>setEntry({...entry,[key]:e.target.value})}/></Field>)}<Field label="Meals, movement, mood & notes"><textarea maxLength={2000} value={entry.note||''} onChange={e=>setEntry({...entry,note:e.target.value})}/></Field></div><button className="button" disabled={a.busy}>{entry.id?'Update record':'Save check-in'}</button>{entry.id&&<button type="button" onClick={()=>setEntry({date:today()})}>Cancel edit</button>}</form><h3>Your history · {d.entries.length} records</h3>{!d.entries.length&&<p>Your first check-in will appear here.</p>}{[...d.entries].sort((a,b)=>b.date.localeCompare(a.date)).map((x:Entry)=><article className="health-record" key={x.id}><div><strong>{x.date}</strong><p>{[['weight','kg'],['waist','cm waist'],['sleep','h sleep'],['water','L water'],['steps','steps'],['energy','/5 energy']].filter(([k])=>x[k]!=null).map(([k,u])=>`${x[k]} ${u}`).join(' · ')}</p><p>{x.note}</p><small>{x.source}{x.edited?' · edited':''}</small></div><div><button onClick={()=>{setEntry(x);window.scrollTo({top:0,behavior:'smooth'});}}>Edit</button><button onClick={()=>{if(confirm('Delete this record?'))save(()=>post('/client/health/health_diary/'+x.id,{},'DELETE'),'Deleted.');}}>Delete</button></div></article>)}</div>}
 {tab==='connections'&&<div className="health-form"><h2>Bring your health records with you.</h2><p>You choose what to share. Files are read on your device; only the previewed measurements are saved after you approve.</p><div className="health-fields"><article><h3>Apple Health</h3><p>Import body-weight records from an Apple Health export.xml file (kg or lb). Direct sync needs a companion iPhone app with HealthKit access.</p><small>Direct sync: not connected</small></article><article><h3>Google / Android</h3><p>Upload a CSV of daily measurements. Live Google Health access needs a configured OAuth application; Health Connect needs an Android app.</p><small>Direct sync: not configured</small></article></div><hr/><h3>Import measurements</h3><p>CSV columns: date, weight, waist, sleep, water, steps, energy, note. Dates use YYYY-MM-DD; units match the diary. Maximum 1,000 rows / 15 MB. Imports are individual readings; overlapping sources are not summed.</p><button className="text-link" onClick={()=>download('health-template.csv','date,weight,waist,sleep,water,steps,energy,note\n'+today()+',,,,,,,\n','text/csv')}>Download blank CSV template</button><Field label="Choose CSV or Apple Health XML"><input type="file" accept=".csv,.xml" onChange={e=>importFile(e.target.files?.[0])}/></Field>{preview.length>0&&<><h3>Review {preview.length} records · {source}</h3><div className="health-preview"><table><thead><tr><th>Date</th><th>Measurements</th><th>Notes</th></tr></thead><tbody>{preview.map((x,i)=><tr key={i}><td>{x.date}</td><td>{[["weight","kg"],["waist","cm waist"],["sleep","h sleep"],["water","L water"],["steps","steps"],["energy","/5 energy"]].filter(([k])=>x[k]!=null&&x[k]!==" ".trim()).map(([k,u])=>`${x[k]} ${u}`).join(" · ")}</td><td>{x.note||"—"}</td></tr>)}</tbody></table></div><label className="health-check"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>I reviewed these records and consent to saving and sharing them with my coach.</label><button className="button" disabled={!approved||a.busy} onClick={async()=>{const r=await save(()=>post('/client/health/import',{entries:preview,source,consent:approved}),'Import complete.');if(r){a.setSuccess(`${r.added} added · ${r.skipped} duplicate records skipped.`);setPreview([]);setApproved(false);}}}><Upload size={18}/>Import reviewed records</button></>}</div>}
 </>}
 </section>;
}
export function HealthReview({clientId}:{clientId:string}){const [d,setD]=useState<Entry|null>(null),[open,setOpen]=useState(false),[error,setError]=useState('');return <div><button className="text-link" onClick={()=>{setOpen(!open);if(!open)api('/admin/clients/'+clientId+'/health').then(setD).catch(e=>setError(e.message));}}>Consultation & health records</button>{open&&<div className="health-review">{error&&<p role="alert">{error}</p>}{d?<><h3>Private consultation history</h3>{!d.intakes.length&&<p>No consultation submitted.</p>}{d.intakes.map((x:Entry)=><details key={x.id}><summary>{new Date(x.created).toLocaleString()}</summary><dl>{groups.flatMap((g:any)=>g[1]).map(([k,label]:string[])=>x[k]!=null&&x[k]!==''&&<div key={k}><dt>{label}</dt><dd>{String(x[k])}</dd></div>)}</dl><small>Consent recorded: {x.consentAt}</small></details>)}<h3>Daily records</h3>{d.entries.map((x:Entry)=><p key={x.id}>{x.date} · {Object.entries(x).filter(([k,v])=>['weight','waist','sleep','water','steps','energy','note','source'].includes(k)&&v!=null).map(([k,v])=>`${k}: ${v}`).join(' · ')}</p>)}</>:!error&&<p>Loading…</p>}</div>}</div>}
